### ISSUE TITLE
Discount Coupons are applied to all items rather than listed separately resulting in confusing invoices. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#10]
![image](https://user-images.githubusercontent.com/58035708/87513230-aaac1180-c678-11ea-8402-ebb59b40c89e.png)

Would you buy an item with a discount invoice as the example seen above, instead of including the discount as a separate item with a negative cost are the discount taken from the separate cost of the items, as can be seen in the picture below.
![image](https://user-images.githubusercontent.com/58035708/87513414-01195000-c679-11ea-92e3-1d7c6d7cee53.png)

This could result in rather confusing invoices for the customers.

**Comment by MichaelBengtsson** [comment]
This is how WooCommerce works as standard. A coupon is applied to all the products in the cart. If you want a discount to show up as its own discounted line, then you need to add it as a negative fee. But this is not the standard in WooCommerce

**Comment by stefanliden** [comment]
the discount code is not visible regardless of the type of discount code in the payment call to Billmate. This means that customers will never be able to see on their invoices that a discount code has been used. Example if a product has received a discount of 10%, it should be sent as this

$ values ["Articles"] [1] = array (
         "artnr" => "B456",
         "title" => "Article 2",
         "quantity" => "3.5",
         "aprice" => "56780",
         "taxrate" => "25",
         "discount" => "10",
         "withouttax" => "178857",
);

If this is not included, customers will call and shop and ask us why they can not see the discount code on their receipts / invoices.We must also be sure that it is possible to give a discount for items even if they have different VAT rates such as 6% 25%

**Comment by NiklasHogefjord** [comment]
@stefanliden How should we add a discount in the request to Billmate if it is a fixed cart amount discount? 

The API-docs mention that it should be sent in as %, but fixed amount coupons can also be created in WooCommerce.

**Comment by NiklasHogefjord** [comment]
@MattiasNilsson Would it be ok to just add the discount on each order line for display/information? Not be a part of the totals calculation? I have tested and it seem to work ok like that.

**Comment by NiklasHogefjord** [comment]
@OskarOstlund perhaps you can test this and see that it looks ok for you as well?

**Comment by OskarOstlund** [comment]
Tested and approved. 

Discounts have now been included in the
