### ISSUE TITLE
Wrong version and client are sent in to the API

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/billmate-checkout-for-woocommerce#105]
Version should be the API version.
Client should be WooCommerce_v2:[pluginversion] - Example: WooCommerce_v2:1.0.0

Currently the below are provided:
Version: WordPress: 5.6. WooCommerce: 4.8.0. BCO:1.0.0. PHP Version: 7.3.26. Krokedil
Client: Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1

**Comment by andyjohansson** [comment]
@MattiasNilsson what API version should be provided?

**Comment by andyjohansson** [comment]
Please verify if the same issue exists in the order management module @NiklasHogefjord.

**Comment by NiklasHogefjord** [comment]
* [PR](https://github.com/Billmate/billmate-checkout-for-woocommerce/pull/108) created for BCO now. 
* Also fixed in BOM via 24301f88921ce0d772b92f6f82b6db0aa6f45fa9

**Comment by stefanliden** [comment]
Tested now and verified that it looks right 👍
