### ISSUE TITLE
Verify that no resources are loaded on pages not needed

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/billmate-checkout-for-woocommerce#106]
In the previous plugin some external resources were loaded on pages not needed. For example colorbox.css
This slowed down the performance of the whole site. All we need to do is to verify that no resources are loaded if not needed.

Posted on behalf of @DanielMarklund

**Comment by andyjohansson** [comment]
One thing to consider while doing this issue is what external resources are loaded if the part payment amounts are shown on the product page. Also, if this setting is disabled, do we load any external resources that are not needed in that use case?

**Comment by NiklasHogefjord** [comment]
The only assets that are loaded in the plugin are bco-checkout.js (or bco-checkout.min.js) and bco-style.css. These two files are only loaded on the checkout page (not on the cart page and not on the order received page).

The image bm_delbetalning_l.png can also be loaded via the part payment widget, but that one is only loaded if activated via settings. No other files are enqueued for that feature at the moment.

**Comment by andyjohansson** [comment]
Great!
