### ISSUE TITLE
Swish payments get order number 0

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#11]
Would you make a swish payment, despite what order number is recorded in the store will BO get an order number of 0.

**Comment by NiklasHogefjord** [comment]
@OskarOstlund How do we simulate a payment via Swish? I don't see any test credentials/phone number for this. When I try with my own phone number I don't see anything in my Swish app. The checkout is waiting for an answer but eventually it reaches a timeout.

![image](https://user-images.githubusercontent.com/985946/89615022-ef952380-d885-11ea-87c0-0fb83d7787c4.png)

**Comment by OskarOstlund** [comment]
There sadly enough is no way to do that with our platform. What I must do when testing it myself is to make a Swish Payment to the Angry Andy Test Account in the live mode and then refund the order. If you want to test things using this method could you contact us and we could refund the swish payments for you.

**Comment by NiklasHogefjord** [comment]
Thanks, I'll get in direct touch with you so we can test this :).

**Comment by andyjohansson** [comment]
Any update here @OskarOstlund or @NiklasHogefjord?

**Comment by andyjohansson** [comment]
Issue is done in the project view but not closed here so I assume that it is not a problem anymore? If so, please close this issue.

**Comment by OskarOstlund** [comment]
This has been fixed.
