### ISSUE TITLE
Add support for Approved and Denied callback order status when order had status Pending previously 

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/billmate-checkout-for-woocommerce#115]
When a order is created with status "Pending" a process is starting at Billmates end to verify the payment. The pending status can be returned when the system identifies a customer behaviour is identified as potential fraud, if a manual credit decision needs to be made, if we are awaiting callback from third party such as Trustly or if a KALP (Kvar att leva på kalkyl) needs to be executed. 

The result of the "Pending" status is always returned to the callback as "Approved" or "Denied". When the status is returned as "Approved" the order is OK to process. If the status "Denied" is returned the order should not be processed and should therefor be cancelled.

Please do note that "Approved" and "Denied" are only returned in the callback. If you make an getPaymentinfo on the order / transaction you will recieve the actual status of the order.

<img width="480" alt="pending_flow" src="https://user-images.githubusercontent.com/4968755/108219260-d70b9d00-7135-11eb-8eb7-5ecade1b05af.png">

**Comment by andyjohansson** [comment]
We can setup account credentials so that this behavior is easy to reproduce for testing purposes.

**Comment by NiklasHogefjord** [comment]
It would be grat if you can set up credentials or information on how to trigger this @andyjohansson

**Comment by andyjohansson** [comment]
Working on it!

**Comment by andyjohansson** [comment]
I will setup a separate account for this purpose for you. Will get back with details over Slack.

**Comment by andyjohansson** [comment]
You should have all the details now to start work @NiklasHogefjord
