### ISSUE TITLE
Reload checkout if customer address is missing during the Woocommerce order creation process

### ISSUE THREAD

**Issue by NiklasHogefjord** [Billmate/billmate-checkout-for-woocommerce#116]

**Comment by NiklasHogefjord** [comment]
This can be tested via [this branch](https://github.com/Billmate/billmate-checkout-for-woocommerce/tree/issue-116) or [this PR](https://github.com/Billmate/billmate-checkout-for-woocommerce/pull/135).

**Comment by andyjohansson** [comment]
@NiklasHogefjord prepeares for a release.
