### ISSUE TITLE
No way to add an invoice fee.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#12]
Currently is there no way for a merchant to add a handling fee when their customer decides to pay through an invoice. In the old module was this a simple textbox where the merchant could write down the price excluding moms and a dropbox where the merchant could add the taxerate on their own (see image attached below).
![P-01](https://user-images.githubusercontent.com/58035708/88024892-c2c9d800-cb33-11ea-827c-f0b920658ac7.png)

**Comment by NiklasHogefjord** [comment]
@OskarOstlund Is it what is described as _handling_ in https://billmate.github.io/api-docs/#initcheckout that is used for Invoice fee?

**Comment by OskarOstlund** [comment]
Yes.

**Comment by NiklasHogefjord** [comment]
OK, we'll take a look at this.

**Comment by OskarOstlund** [comment]
This needs to be fixed a bit more. 

From what I can see does it take the last VAT in the standard VAT rate, in my case do I have a list of three, 25%, 12%, and 6% thusly my VAT is 6% for the invoice fee. 

![image](https://user-images.githubusercontent.com/58035708/94777254-73214b80-03c3-11eb-9347-c1037bdb2036.png)
As can be seen in the picture above does this causes some issues, in the checkout is the "correct" 10.60 SEK displayed as the cost of the handling fee which is highlighted in red. This is the value that is sent in to BO. However when you are redirected to the success URL have the handling been bumped up to a 25% VAT as highlighted in yellow. This value is what is saved in the store causing a discrepancy in BO and the store. It further more does not update the BO order number as can also be seen highlighted in red.

**Comment by NiklasHogefjord** [comment]
I think this is a configuration issue in your store @OskarOstlund. Here are examples of how I change the vat rate in the plugin settings and how it is changed in the BCO checkout:

## Standard vat rate (25%):
![image](https://user-images.githubusercontent.com/985946/94789178-e1223e80-03d4-11eb-9036-bc34bc5b57ab.png)
![image](https://user-images.githubusercontent.com/985946/94789211-ebdcd380-03d4-11eb-9461-04a3545e927a.png)

## Without vat:
![image](https://user-images.githubusercontent.com/985946/94789296-08790b80-03d5-11eb-8633-b9fbb8592fd8.png)
![image](https://user-images.githubusercontent.com/985946/94789315-0f078300-03d5-11eb-9e9f-9037bc67e09c.png)

## Reduced rate (12%):
![image](https://user-images.githubusercontent.com/985946/94789432-31999c00-03d5-11eb-81a9-0c5a7a4afc8d.png)
![image](https://user-images.githubusercontent.com/985946/94789480-3fe7b800-03d5-11eb-95bc-7c62eca63d5d.png)

## 6% vat rate:
![image](https://user-images.githubusercontent.com/985946/94789595-63aafe00-03d5-11eb-92e9-a8188f8caf13.png)

![image](https://user-images.githubusercontent.com/985946/94789641-71f91a00-03d5-11eb-9fd0-1ce2e2fe9127.png)


Regarding _It further more does not update the BO order number as can also be seen highlighted in red._ This is still an issue in Billmates system. I would like you to follow up on this.

**Comment by OskarOstlund** [comment]
This is due to as I said in my text because I have three different VAT rates in my standard VAT, it is not the correct way to set up a store no, but it is not entirely unreasonable that a person would set up their store that way, especially a non-professional.  To clarify can you see the incorrect setup I tested with below: 
![image](https://user-images.githubusercontent.com/58035708/95046719-08cf1a80-06e5-11eb-9fc7-2567712830aa.png)

I do however still feel like the issue here is not the store being incorrectly set up but the fact that the module collects the standard VAT rates in different ways as it at times get the 25% one and at others the 6% one. I will however leave it up to @MattiasNilsson to determine if this should be fixed or we will just tell the merchants to set up their stores correctly.

**Comment by MattiasNilsson** [comment]
My opinion is that this is an Merchant issue, they can mess it up in many ways.
