### ISSUE TITLE
Make scrolling to iframe optional

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/billmate-checkout-for-woocommerce#129]
Make automatic scrolling to the checkout iframe optional. We've moved order review, shipping options and added some content above the BCO iframe which we want the customers to see when entering the checkout. With the line below uncommented, the customer gets scrolled past all content. I've attached a screenshot on what I mean with the added/moved content.

**bco-checkout.js, line 198:**
`$('html, body').animate({scrollTop: $(document).find( "#checkout" ).offset().top + json.data}, 400);`

<img width="1211" alt="Skärmavbild 2021-03-14 kl  09 27 30" src="https://user-images.githubusercontent.com/1516103/111062242-fc2acb80-84a7-11eb-8936-7150e22bbfff.png">

**Comment by NiklasHogefjord** [comment]
Fixed and released in v1.5.0
