### ISSUE TITLE
Disable BCO iframe interaction on update_checkout event

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/billmate-checkout-for-woocommerce#130]
On slower connection speeds (customer or server), when a user changes the shipping method – it takes a few seconds for the BCO iframe to refresh with the new data. ~This is due to the iframe only updating on the updated_checkout js event.~ _(Edit: not sure about this anymore as I couldn't find it in your code)_ I've attached a video to show the issue in action.

We've been experiencing issues in the old Billmate Checkout where a price mismatch occurs (shipping fee mismatch between Woo and Billmate) and I think I finally figured out the culprit. In the new BCO the order is luckily not being processed if the WooCommerce data and the BCO data doesn't match.

**Video:**
The video is from my local dev environment which is much slower than our production server.
https://user-images.githubusercontent.com/1516103/111062782-68f39500-84ab-11eb-8891-697d6db00ab0.mov

**Steps to reproduce:**
1. Server has a slow connection.
2. Customer enters the checkout and selects a free shipping option.
3. Customer enters all details in BCO and is ready to checkout.
4. Customer changes the shipping option to something expensive.
5. The order-review is refreshing (slowly), but the price is still the same in BCO.
6. The customer checks out before BCO has refreshed.
7. The error message "Vi kunde inte behandla din order, vänligen försök igen." appears (failed order) and the BCO iframe is stuck in a refresh loop.

**Recommended solution:**
~Add a javascript event trigger on the update_checkout js event. When the event is triggered, disable iframe interaction and fade it to 0.5 opacity. Enable it again and change opacity to 1 on the updated_checkout js event. Perhaps also show a loading indicator to make the user experience better.~

**Edit:** I now noticed that you can just trigger the lock/unlock postMessage, so it should probably be used.

```
checkout_iframe.postMessage('lock', '*');
checkout_iframe.postMessage('unlock', '*');
```

As you need to use jQuery to catch the update_checkout and updated_checkout, a quick solution to this is:
`jQuery('body').on('update_checkout', () => checkout_iframe.postMessage('lock', '*')).on('updated_checkout', () => checkout_iframe.postMessage('unlock', '*'));`

**Comment by NiklasHogefjord** [comment]
After discussing this with Billmate we came to the conclusion to _not_ implement this at the moment. 

The reason is that we already have tried to implement this feature with the result that the actual update of the Billmate iframe is happening _after_ we have triggered the unlock event. This was a user experience Billmate suggested we should avoid.

Currently we can not do anything to solve this from the plugin side. I think a tweak is needed in Billmates system before we can implement it in the plugin.
