### ISSUE TITLE
Add wrapper (before/after) actions to the templates/billmate-checkout.php

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/billmate-checkout-for-woocommerce#131]
We're doing a lot of customizations on the checkout page, which includes moving cart contents, shipping method etc from the regular WooCommerce checkout table to their own separate sections. The current template actions are working fine, but for even better customization options I suggest adding a few more actions in the templates/billmate-checkout.

### Current billmate-checkout template actions:
bco_wc_before_checkout_form
bco_wc_before_wrapper
bco_wc_before_order_review
bco_wc_after_order_review
bco_wc_after_wrapper
bco_wc_after_checkout_form
bco_wc_before_billmate_checkout_form
bco_wc_after_billmate_checkout_form

### Suggested template actions (bold = new):
bco_wc_before_checkout_form
bco_wc_before_wrapper
**bco_wc_before_order_review_wrapper**
bco_wc_before_order_review
bco_wc_after_order_review
**bco_wc_after_order_review_wrapper**
bco_wc_after_order_review
bco_wc_after_wrapper
bco_wc_after_checkout_form
**bco_wc_before_billmate_checkout_form_wrapper**
bco_wc_before_billmate_checkout_form
bco_wc_after_billmate_checkout_form
**bco_wc_after_billmate_checkout_form_wrapper**

### Final template

Not as pretty as current template, but with a few more actions for us developers to use.

```
<?php
/**
 * Billmate_Checkout checkout page
 *
 * Overrides /checkout/form-checkout.php.
 *
 * @package Billmate_Checkout/Templates
 */

wc_print_notices();
do_action( 'bco_wc_before_checkout_form' );
// If checkout registration is disabled and not logged in, the user cannot checkout.
if ( ! $checkout->is_registration_enabled() && $checkout->is_registration_required() && ! is_user_logged_in() ) {
	echo esc_html( apply_filters( 'woocommerce_checkout_must_be_logged_in_message', __( 'You must be logged in to checkout.', 'woocommerce' ) ) );
	return;
}
?>
<form name="checkout" class="checkout woocommerce-checkout">
	<?php do_action( 'bco_wc_before_wrapper' ); ?>
	<div id="bco-wrapper">
		<?php do_action( 'bco_wc_before_order_review_wrapper' ); ?>
		<div id="bco-order-review">
			<?php do_action( 'bco_wc_before_order_review' ); ?>
			<?php woocommerce_order_review(); ?>
			<?php do_action( 'bco_wc_after_order_review' ); ?>
		</div>
		<?php do_action( 'bco_wc_after_order_review_wrapper' ); ?>
	</div>
	<?php do_action( 'bco_wc_after_wrapper' ); ?>
</form>
<?php do_action( 'bco_wc_after_checkout_form' ); ?>
<?php do_action( 'bco_wc_before_billmate_checkout_form_wrapper' ); ?>
<div id="bco-iframe">
	<?php do_action( 'bco_wc_before_billmate_checkout_form' ); ?>
	<?php bco_show_iframe(); ?>
	<?php do_action( 'bco_wc_after_billmate_checkout_form' ); ?>
</div>
<?php do_action( 'bco_wc_after_billmate_checkout_form_wrapper' ); ?>
```

**Comment by NiklasHogefjord** [comment]
Hi @DanielMarklund,

Would it be ok for you to have another look at this now when the template file is updated to this: https://github.com/Billmate/billmate-checkout-for-woocommerce/blob/issue-checkout-layout/src/templates/billmate-checkout.php

**Comment by DanielMarklund** [comment]
Hi @NiklasHogefjord, sorry for the late feedback. I'm happy with the template file changes! Thank you.

**Comment by NiklasHogefjord** [comment]
Great, thanks!
