### ISSUE TITLE
Updating cart contents (quantity) doesn't refresh BCO

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/billmate-checkout-for-woocommerce#132]
When adding the ability to change quantity of products on the checkout page, BCO does not refresh when changing quantities, so there is a price mismatch.

**Steps to reproduce:**
1. Install "Krokedil Checkout Customizer for WooCommerce" (by @NiklasHogefjord <3)
2. Add something to the cart
3. Go to checkout
4. Update the product quantity
5. The review-order updates with the correct new price, but BCO still has the previous price.

**Video:**
https://user-images.githubusercontent.com/1516103/111065218-eb368600-84b8-11eb-84a6-f09951dc4911.mov

**Comment by DanielMarklund** [comment]
Trying some things out. Executing this manually in the console after reproducing the steps above does not update the price even if the iframe is reloaded:
`checkout_iframe.postMessage('update', '*');`

So there is some stored data not being updated somewhere. Will keep investigating.

**Comment by DanielMarklund** [comment]
Check above mentioned issue for a temporary fix, or go to comment in issue #133:
https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/133#issuecomment-799388057)

**Comment by NiklasHogefjord** [comment]
Hi @DanielMarklund
Thanks for using our plugins but "Krokedil Checkout Customizer for WooCommerce" is not maintained at the moment. Could you please test with https://sv.wordpress.org/plugins/change-quantity-on-checkout-for-woocommerce/ and see if that solves your issue? :)

**Comment by DanielMarklund** [comment]
Hi @NiklasHogefjord, I had the same issue with a few other plugins. Haven't tried the one you mentioned though. https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/133#issuecomment-799388057 made it work even with the not maintained plugin.

**Comment by NiklasHogefjord** [comment]
Hi @DanielMarklund, 
Since we're aiming at releasing a new version with the template change related to #133, I will close this as solved when the release is live. 

Thanks for your feedback!

**Comment by andyjohansson** [comment]
Hi @DanielMarklund, could you please test and verify if release 1.2.0 solved the issue?
