### ISSUE TITLE
Validate phone number input

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/billmate-checkout-for-woocommerce#137]
Perhaps this issue is only related to the BCO iframe (as phone number input is handled outside the plugin), but I figured I'd post it here just in case. We've had a lot of issues where customers write their phone numbers in different formats, many of the times cutting off the last digit. It seems to happen when customers write 46 in the beginning.

Example: A customer owns the number 0712345678, but types 46 (area code) in the beginning. The phone number in the order data then becomes 4671234567, which is missing the last digit. The result is a lot of manual corrections needed and some customers not receiving SMS tracking links etc.

**Comment by NiklasHogefjord** [comment]
Closing tis since it isn't related to this plugin.
