### ISSUE TITLE
Cancelled invoice PDF still shows old payment.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#14]
Would you cancel an invoice from the woocommerce module is the order cancelled in our system, however the PDF invoice does not get updated in BO. This is in contrast to when one makes a cancelpayment API call manually where the PDF is updated to say that the customer should not pay anything.

**Comment by NiklasHogefjord** [comment]
Not sure I understand this @OskarOstlund. We use cancelPayment for this. Is it something that needs to be changed in the request or do we need to make yet another request to update the PDF invoice in BO?

**Comment by OskarOstlund** [comment]
No, cancel payment should be enough, making a manual cancelPayment APIcall to one of the invoices created by the module do however update the attached PDF correctly. Having dug around is this due to the cancelPayment API call made by the module does not include BILLMATE_SERVER and BILLMATE_CLIENT, this does not update the PDF in BO.
![image](https://user-images.githubusercontent.com/58035708/89259218-2111b300-d62a-11ea-8e7e-55c6f843a403.png)
Above can we see a manual cancelPayment call I made to the left and one the module made to the right. As you can see is there neither a version nor a client listed in the cancelPayment call. This is not universal as the addPayment call has them.

**Comment by NiklasHogefjord** [comment]
Not sure what we should do with this one @OskarOstlund?

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord What we need to add to the header should be something like this:

BillmateCheckoutWooCommerce:ThePluginVersionCurrentlyRun

**Comment by NiklasHogefjord** [comment]
We do add version and client (since of August 14). Can you test this again and see if you still experience issues @OskarOstlund ?

**Comment by MattiasNilsson** [comment]
This works as expected.
