### ISSUE TITLE
Disable checkout if no delivery method exists. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#144]
![image](https://user-images.githubusercontent.com/58035708/115518422-6d6c5400-a288-11eb-8d70-2560282d2bb0.png)
As we can see in the image attached above is it possible to still finish an order if delivery method is available for your zip address. We should most likely attempt to block the ability of the customer to finish an order if no delivery method is available.

**Comment by NiklasHogefjord** [comment]
Hi,
It is not possible to finish this order. When trying to click the "Slutför köp" button the customer will see the following error notice from Woocommerce:

![image](https://user-images.githubusercontent.com/985946/115710259-6e79b000-a372-11eb-8c38-457ea22acd1d.png)
