### ISSUE TITLE
Critical: Selected payment method not always stored

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/billmate-checkout-for-woocommerce#145]
We have finally implemented the new BCO and pushed it live. It has been running over night now and a lot of orders are missing the selected payment method. This problem was also present in the older plugin but was not very common (also was only present on Swish payments).

This is a critical error for us as that info is used in the ERP we use, so the ERP knows the correct payment method.

It has occurred for both Card Payment and Swish so far.

**Orders overview:** "via Billmate Checkout"
**Order overview:** Betalning via Billmate Checkout (_TRANSACTION ID_)

I've attached a screenshot from the orders overview.

BCO version: 1.1.1

![Namnlöst-1](https://user-images.githubusercontent.com/1516103/116522639-b5692780-a8d5-11eb-96c2-c6cc1d0ce5d1.jpg)

**Comment by NiklasHogefjord** [comment]
Hi Daniel,
Get in touch with Billmate support directly regarding this issue. We will need to look into the payment gateway logs in order to see what has happened here.

**Comment by DanielMarklund** [comment]
I made Stefan at Billmate aware of this and he has passed it on to their developers. @NiklasHogefjord

**Comment by OskarOstlund** [comment]
@DanielMarklund 
Would it be possible for you to resend the gateway logs here? they seems to have been left with Stefan when he left the company.

**Comment by NiklasHogefjord** [comment]
Closing this ticket since we don't have access to the logs. Please feel free to re-open it if you have more information regarding the issue @DanielMarklund (or if you can email Billmate logs for a failed purchase).

**Comment by DanielMarklund** [comment]
I have already sent more information to Billmate June 4th. Was sent to @OskarOstlund. I've been waiting for a solution on this.

**Comment by DanielMarklund** [comment]
@OskarOstlund I have re-sent the information to your direct e-mail, with the title "Underlag till issue 145".

**Comment by NiklasHogefjord** [comment]
Hi @DanielMarklund, did you send the logs for the entire purchase sequence? I would need to look into details here :)
