### ISSUE TITLE
Billmate checkout hash is missing

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/billmate-checkout-for-woocommerce#150]
Some customers are experiencing an issue with "Billmate checkout hash is missing". Last time this happened I had to clear all user sessions and open carts.

When debugging #146 I changed our tax calculations to not include VAT on shipping. When I saved it and refreshed the checkout, the hash error happened for me as well. After reverting the change it still was there. I'm unable to get past the error and cannot checkout.

Is the session data cleared when updating WooCommerce settings? Shouldn't BCO update the hash in case it is missing?

The following session data is empty when this happens:
WC()->session->get( 'bco_wc_hash' );

The error is thrown in class-bco-ajax.php in the function bco_wc_update_checkout().

**Console also gave me the following error:**
```
Uncaught TypeError: Cannot read property 'redirect_url' of undefined
    at Object.complete (bco-checkout.js:301)
    at c (jquery.min.js?ver=3.5.1:2)
    at Object.fireWith (jquery.min.js?ver=3.5.1:2)
    at l (jquery.min.js?ver=3.5.1:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js?ver=3.5.1:2)
```

gz#174132

**Comment by DanielMarklund** [comment]
I've been doing some debugging on this issue when the error happens.

**Var dumping `BCO_WC()->api->request_get_checkout( WC()->session->get( 'bco_wc_hash' ) );` shows the following error code:**
`Billmate Error Code: 50015. Checkout: Hash var tom`

**The session data is missing following keys:**
bco_wc_number
bco_wc_checkout_url
bco_wc_hash

**The session data still has the following set:**
bco_wc_temp_order_id

---

**Proposal**
If bco_wc_hash is missing in user session data, init a new checkout and set a new hash. Would it be possible @NiklasHogefjord ? I'm trying to fix this temporarily myself as a lot of customers are reporting this issue (losing sales).

**Comment by andyjohansson** [comment]
We need to discuss this some more @NiklasHogefjord.

**Comment by NiklasHogefjord** [comment]
Is this still an issue for you @DanielMarklund? We have released a couple of new versions and I can not reproduce this issue anymore.

**Comment by NiklasHogefjord** [comment]
Closing this for now. Please feel free to re-open it if it happens again.
