### ISSUE TITLE
updating an order in store does not update it in BO. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#16]
Would a merchant attempt to update their order in their store by adding or removing items will this update in the store, however no update payment apicall is made. This leaves a discrepancy between the store and the BO website. 

![P-01](https://user-images.githubusercontent.com/58035708/88764814-e6190680-d175-11ea-9afa-ecdc7543b4c3.png)
As can be seen above do we have one order in the store that has items added to it, but we also have a different order in BO that is the original order made but differs from the newly updated version.

**Comment by NiklasHogefjord** [comment]
I will get in touch with you @MattiasNilsson before we proceed with this issue.

**Comment by anfly0** [comment]
@MattiasNilsson @NiklasHogefjord 
Why is this issue closed?  
Is it supposed to be fixed or are we not fixing it?
I can't get this to work at all. I'm having the exact same issue as in the description.

**Comment by NiklasHogefjord** [comment]
@anfly0 It is fixed because it's solved and merged into the Master branch of the Billmate Order Management plugin. Are you using the latest version and have follow this instructions: https://docs.krokedil.com/article/366-billmate-order-management-introduction#h-H2_4

**Comment by anfly0** [comment]
@NiklasHogefjord There seems to be an issue with editing orders that have been created with status "Pending".
In the edit order view, they show as "On hold" and it is possible to edit the order, and clicking save updates the order in the store but do not affect the invoice in billmate online. 
I don't know what discussions you have had with @MattiasNilsson, but I would expect the update to either succeed or fail completely.

**Comment by NiklasHogefjord** [comment]
@anfly0 This is what Billmate docs say about updating an order:
_NOTE: You can only update a payment that has status “Created”, which has not yet been locked (sent)_.

If Order updates is enabled in the Order Management plugin, do you want the plugin to add an order note in WooCommerce if the status is anything else than _Created_ and an update of the order is done in Woo?

**Comment by OskarOstlund** [comment]
Something I noticed that might need to be updated in the documentation or at least looked over, the steps as described in would be enough to send two separate update payments API calls. Maybe should some clarification be added that merely pressing either "Save" or "Recalculate" would be enough to create an update payment.

If nothing else just because it would be simpler for someone that needs to add just one item to their order to press "recalculate" when they are redirected back rather than once again press to edit one item or to add one item, then save, then recalculate, and then be done.  It might also be a bit confusing for someone that just wants to add one new item to the order as the current version is exclusively made with editing the already placed items in mind.
