### ISSUE TITLE
As a customer, i want to be able to handle orders from the nordic countries

### ISSUE THREAD

**Issue by JohnssonM** [Billmate/billmate-checkout-for-woocommerce#160]
By today we only support Swedish customers and consumers with swedish addresses and phone numbers.
With this implementation we change that so we can support consumers from Finland, Norway and Denmark.
Note: We will only support customers (our customers) from Sweden or with swedish Org.Number

The Checkout is translated to english aswell for the international consumers.

### Acceptance criteria

Implement support for Finland with EUR
Implement support for Denmark with DKK
Implement support for Norway with NOK
Implement support for english translation in the checkout

### Documentation
https://billmate.github.io/api-docs/?json#initcheckout

**Comment by NiklasHogefjord** [comment]
Tested and works with SEK, EUR, DKK & NOK.

**Comment by NiklasHogefjord** [comment]
Released in https://github.com/Billmate/billmate-checkout-for-woocommerce/releases/tag/1.4.0
