### ISSUE TITLE
Make private magic functions public

### ISSUE THREAD

**Issue by kalorifri** [Billmate/billmate-checkout-for-woocommerce#162]
https://github.com/Billmate/billmate-checkout-for-woocommerce/blob/master/src/billmate-checkout-for-woocommerce.php#L73
https://github.com/Billmate/billmate-checkout-for-woocommerce/blob/master/src/billmate-checkout-for-woocommerce.php#L82

Make Billmate_Checkout_For_WooCommerce::__clone and Billmate_Checkout_For_WooCommerce::__wakeup public

Because of PHP 8

gz#177257

**Comment by NiklasHogefjord** [comment]
Fixed and released now.
