### ISSUE TITLE
Merchant has reported that the invoice fee is written twice.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#164]
![image](https://user-images.githubusercontent.com/58035708/129894826-b5df801c-749d-4a15-b8b1-56eb53d6a0cd.png)
As can be seen in the image attached above have we received complaints that some merchants has invoice fee written twice

**Comment by NiklasHogefjord** [comment]
We released a new version of the plugin yesterday that should fix the issue. @OskarOstlund can you check if it still happens with version 1.3.0?

**Comment by NiklasHogefjord** [comment]
Closing this. Feel fre to re-open it if it still happens.
