### ISSUE TITLE
customer at times missing clarification what purchase was made.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#166]
![image](https://user-images.githubusercontent.com/58035708/133740289-95ee1177-745d-49b6-a84f-9a1c7bb6cce2.png)
As can be seen in the image above do we have a merchant that when she looks through her list of orders are there times where the exact method used to pay was excluded. As can be seen in the picture above is 49257, 49255, and 49253 listed with their appropriate payment method but 49256, and 49254 

gz#182329

**Comment by NiklasHogefjord** [comment]
I'll look into this next week.

**Comment by DanielMarklund** [comment]
This is exactly the same issue we have (#145). Sometimes when this happens, we get contacted by customers who tells us that the checkout was stuck on loading and they didn't get an order confirmation to their e-mail.

**Comment by NiklasHogefjord** [comment]
Fixed and released in v 1.5.0.
