### ISSUE TITLE
If you change currency mid purchase will that result in different currencies in BO and the store. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#168]
![image](https://user-images.githubusercontent.com/58035708/135062268-b1021cac-74ac-410e-893e-dd563576642a.png)

If you start up a checkout and then in a separate tab go to the admin or through whatever method the store uses change the currency will billmate online show one currency, the one that you had chosen when you started the checkout. If you attempt to start a purchase with Sek for instance, and then start the checkout, change the currency in another tab to DKK. and complete the checkout will BO claim that the invoice is placed in SEK while the store will claim that it is placed in DKK as can be seen in the picture above.

**Comment by NiklasHogefjord** [comment]
Fixed and released.
