### ISSUE TITLE
Articles with a negative cost does not get a taxrate.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#17]
Would you buy a product that cost less than zero will the store calculate the correct moms, however the addPayment API call made to BO will have a tax of 0 resulting in different costs in the store and the invoices generated by BO. 
![P-01](https://user-images.githubusercontent.com/58035708/88785450-7e70b480-d191-11ea-8746-57c7b32f2d2d.png)

**Comment by NiklasHogefjord** [comment]
@OskarOstlund Can you provide me with a scenario when a negative cost with a negative vat is used? How do you set this up in your store?

**Comment by OskarOstlund** [comment]
I created an article with the cost of -20 SEK in the store as can be seen below: 
![image](https://user-images.githubusercontent.com/58035708/89255185-5d8ce100-d621-11ea-9628-cde0e381d5de.png)
This would then simply create a vat from the item that is negative as can be seen in the completed order in the store vs the invoice in BO. As you can see below do the item with a cost of -20 SEK has a negative vat of -4 SEK in the woocommerce store resulting in a total VAT of 4 SEK (8 + (-4) = 4). However in BO are we given a VAT of 8 SEK (in this case 8 + 0 = 8).
![image](https://user-images.githubusercontent.com/58035708/89255763-c4f76080-d622-11ea-93a9-038ace5e43a7.png)

**Comment by NiklasHogefjord** [comment]
Thanks @OskarOstlund!
