### ISSUE TITLE
Pay for Order should not exist as an alternative

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#18]
You can currently chose between Pay for Order and billmate checkout flow in the billmate setting page, this is entirely pointless as the pay for order only adds an alternative to use the billmate checkout. This setting should be removed entirely and the merchant should only be able to use the checkout. 

![image](https://user-images.githubusercontent.com/58035708/88898054-83466e80-d24c-11ea-9d2a-878a793e34f4.png)

**Comment by NiklasHogefjord** [comment]
@OskarOstlund I agree that the _Pay for order_ wording in the setting isn't very good at all. However, our intention here was that this could be an alternative checkout flow for merchants that have features in the checkout that isn't compatible with an embedded iframe based checkout.

But if you want us to remove this setting we will do that.
