### ISSUE TITLE
Mixes tabs and spaces in assets/js/bco-checkout.js

### ISSUE THREAD

**Issue by MattiasNilsson** [Billmate/billmate-checkout-for-woocommerce#2]
The file should be changed to contain spaces only. So 1 tabs -> 4 spaces.

Mixes tabs and spaces in assets/js/bco-checkout.js

**Comment by Kristian-Andersson** [comment]
Fix: https://github.com/Billmate/billmate-checkout-for-woocommerce/commit/e158367f4364ed7231c660cb3579c377e4418182
