### ISSUE TITLE
Version and Client is missing from some APIcalls.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#20]
Related to https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/14

Some APIcalls lacks both BILLMATE_SERVER and BILLMATE_CLIENT in the API calls, these are at the very least;

* activatePayment
* cancelPayment. 
* getPaymentinfo.
* updatePayment.

it is not known if it works or not for other APIcalls except add payment where these are saved.

**Comment by NiklasHogefjord** [comment]
I'm guessing that it is version and client in this part you are referring to @OskarOstlund https://billmate.github.io/api-docs/#authentication.

Is it ok to use it like the following:

**version**: BCO [current Billmate Checkout for WooCommerce version]. WC [current WooCommerce version].
**client**: Customers user agent
