### ISSUE TITLE
card and bank payments gets no updatePayment API call updating ordernumber.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#22]
As the title suggest are no updatePayment API call made to update the order number. This means that while the order number is saved as for an example 129 in the store are all numbers saved as 0 in BO resulting in confusion when one needs to double check the order there compared to the one in the module. 
![image](https://user-images.githubusercontent.com/58035708/89521298-89ee5c00-d7df-11ea-8e85-4c88c20f3d6b.png)
![image](https://user-images.githubusercontent.com/58035708/89521355-9ffc1c80-d7df-11ea-8d06-e6bb091786ef.png)
This can be seen in the two pictures above the first depicting the order in the store and BO respectively. The second one shows the statuslogg of the order in BO. As you can see has no UpdatePayment call been made that changes the order number from 0. 

This is most likely also true for Swishpayment but that got made as a seperate ticket earlier.

**Comment by NiklasHogefjord** [comment]
We will look into this. It seems that we get timeouts from time to time in our requests to your server. We will try to increase the timeout time to see if that solves the issue.

**Comment by NiklasHogefjord** [comment]
@OskarOstlund This should have been fixed now via d08c00560bfb91d4d0a436e03b542ed220ef05a5 and 22d6552850033908ef526daa862d6f8ab0fb795a

**Comment by OskarOstlund** [comment]
Are those changes committed to the master branch yet? Because it is not working when I attempt to place an order with a bank transfer at the very least; 
![image](https://user-images.githubusercontent.com/58035708/92085416-141ee580-edc9-11ea-8c83-50272d9019ac.png)

**Comment by NiklasHogefjord** [comment]
You are correct @OskarOstlund, something isn't correct with Bank transfer.

An updatePayment call is triggered for me but I get the following response:

```
"body": {
		"code": "5216",
		"message": "Det g\u00e5r ej att uppdatera en bank eller kortbetalning.",
		"logid": "39079843"
	}
```

If it isn't possible to update the webstore Order ID in this sequenze we have a major problem with the current checkout/order creation flow.

**Comment by OskarOstlund** [comment]
![image](https://user-images.githubusercontent.com/58035708/92895387-bd925680-f41b-11ea-97ee-6b44f6ca6012.png)
This is also still the case for cardpayments, making them impossible to interact with for the order manager.

**Comment by NiklasHogefjord** [comment]
You are correct @OskarOstlund. However, I need to discuss this closer with Mattias before we have a solution for this problem. I'm talking with him on Monday so I hope to have a solution after that.

**Comment by OskarOstlund** [comment]
Right, I am holding my thumbs that it works out.

**Comment by NiklasHogefjord** [comment]
It was fixed for a while @OskarOstlund but something seems to be broken again. @MattiasNilsson is looking into it.

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord The blocker is now gone, so can be fixed.

**Comment by NiklasHogefjord** [comment]
This issue is now fixed due to changes in Billmates system (logic regarding the purchase_complete event).
