### ISSUE TITLE
cURL error timeout

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#23]
One issue that at times appear when one makes a purchase is that the order comes through and you are directed to the success page, however despite that does a warning appear that says cURL error 28: Operation timed out after 5000 milliseconds with 0 bytes received.

It does not happen every time an order is placed and in rare instances does it happen even with the checkout. This can be seen in the two images attached below: 
Order success URL displaying the error message: 
![image](https://user-images.githubusercontent.com/58035708/89874469-2c318980-dbbc-11ea-92b4-0f536a8a6bc5.png)

checkout where the API is displaying the same error message: 
![image](https://user-images.githubusercontent.com/58035708/89874520-3ce1ff80-dbbc-11ea-8998-cecbae96f0cc.png)

**Comment by NiklasHogefjord** [comment]
@OskarOstlund Can you test the Develop branch? We have bumped the timeout time to 10 seconds now.

**Comment by OskarOstlund** [comment]
I am currently on that branch, however it was a few days since I updated it so I can give it another go and see if I can get the issue to appear again.

**Comment by OskarOstlund** [comment]
This seems to have been fixed as I have been unable to reproduce the error during testing.

**Comment by NiklasHogefjord** [comment]
Sounds good. Fixed in 22d6552850033908ef526daa862d6f8ab0fb795a. Closing this now.
