### ISSUE TITLE
The cart checkout-left is still interactive on successURL 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#24]
![image](https://user-images.githubusercontent.com/58035708/89885482-6c4c3880-dbcb-11ea-865b-1326fb8826cb.png)

As can be seen above when you are redirected to the billmate success URL are the menu on the left of the billmate module still interactive. While the order does not change and has the correct prize on it when one is taken to the final success URL. However the fact that one can update the interface and see the prize change could be very confusing for customers.

**Comment by NiklasHogefjord** [comment]
@MattiasNilsson & @OskarOstlund I have a branch here https://github.com/Billmate/billmate-checkout-for-woocommerce/tree/issue-%2324, that adds a modal over the entire page. It looks like this at the moment but can be improved.

![image](https://user-images.githubusercontent.com/985946/92081020-bdaea880-edc2-11ea-8624-33c628edd99c.png)


Would that be ok?

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord That looks good to me! So go ahead!

**Comment by NiklasHogefjord** [comment]
Thanks! Merging it to master.
