### ISSUE TITLE
Paying for the same order twice results in a fatal error 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#29]
If you create an order and then open the checkout in two different tabs and pay with card payment are you met with the following error message: 

Billmate Error Code: 50015. Checkout: Hash var tom

Fatal error: Uncaught Error: Call to a member function set_payment_method_title() on bool in C:\xampp\htdocs\WoocommerceKrokodil\wp-content\plugins\billmate-checkout-for-woocommerce\includes\bco-functions.php:163 Stack trace: #0 C:\xampp\htdocs\WoocommerceKrokodil\wp-content\plugins\billmate-checkout-for-woocommerce\billmate-checkout-for-woocommerce.php(182): bco_set_payment_method_title(NULL, false) #1 C:\xampp\htdocs\WoocommerceKrokodil\wp-includes\class-wp-hook.php(287): Billmate_Checkout_For_WooCommerce->confirm_order('') #2 C:\xampp\htdocs\WoocommerceKrokodil\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 C:\xampp\htdocs\WoocommerceKrokodil\wp-includes\plugin.php(478): WP_Hook->do_action(Array) #4 C:\xampp\htdocs\WoocommerceKrokodil\wp-settings.php(540): do_action('init') #5 C:\xampp\htdocs\WoocommerceKrokodil\wp-config.php(90): require_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\WoocommerceKrokodil\wp-load.php(37): require_once('C:\\xampp\\htdocs...') #7 C:\xampp\htdocs\WoocommerceKro in C:\xampp\htdocs\WoocommerceKrokodil\wp-content\plugins\billmate-checkout-for-woocommerce\includes\bco-functions.php on line 163
Ett kritiskt fel har inträffat på din webbplats.

Lär dig mer om felsökning i WordPress.

Despite the fatal error is however an order created twice in BO but only once in the store.

**Comment by NiklasHogefjord** [comment]
Tested now. Seems as this has been solved when I improved the flow for confirmation of the order in Woo and update the payment number in BO.
