### ISSUE TITLE
Remove all console.log from assets/js/bco-checkout.js

### ISSUE THREAD

**Issue by MattiasNilsson** [Billmate/billmate-checkout-for-woocommerce#3]
Remove all console.log from assets/js/bco-checkout.js to have a proper Production output.

**Comment by NiklasHogefjord** [comment]
One idea @MattiasNilsson. 

Let's introduce a minified version of the file (bco-checkout.min.js) file that doesn't include any console.log. But if SCRIPT_DEBUG is defined in wp-config.php the regular bco-checkout.js file is enqueued and the console.log is still there. That would make it a bit easier in some troubleshooting scenarios.

Would that be ok?

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord That sounds perfect!

**Comment by NiklasHogefjord** [comment]
Great, thanks :)
