### ISSUE TITLE
Custom approved order status setting

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#31]
You should be able to choose what the status of the order should be when a purchase has been made with Billmate Checkout in normal cases it should be processing but if you have selected completed as status then the order should automatically send an activatePayment to Billmate so customers do not change the status manually. 

![image](https://user-images.githubusercontent.com/13320183/90123192-b6b1ee80-dd5e-11ea-9865-cf2cd59e4b0e.png)

**Comment by NiklasHogefjord** [comment]
We did talk about this before we started the project. My suggestion was to use the function `payment_complete()` and let WooCommerce handle what status the order should be changed to (and send the appropriate emails). This was accepted by Billmate team. 

My suggestion is that we go with what we decided earlier.

**Comment by MattiasNilsson** [comment]
As stated we are using that approach as we spoke of in the beginning.
