### ISSUE TITLE
View order listings on the Checkout page.

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#32]
There should be a setting in the setting  to choose whether you want customers to write a message or not to the store. This text will been shown the WooCommerce order detail view. 

![image](https://user-images.githubusercontent.com/13320183/90123831-b8c87d00-dd5f-11ea-97a4-0126f4d98a80.png)
![image](https://user-images.githubusercontent.com/13320183/90123920-dc8bc300-dd5f-11ea-9c08-3a7358d7e68c.png)

**Comment by NiklasHogefjord** [comment]
This does not have to be included in a payment gateway setting. My suggestion is that this is handled site wide instead by the merchant.

There is a filter that can be used for hiding the Customer note field:

`add_filter( 'woocommerce_enable_order_notes_field', '__return_false' );`

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord Why WontFix?

**Comment by NiklasHogefjord** [comment]
@MattiasNilsson Why should it be a setting in a specific payment method?
