### ISSUE TITLE
Setting for send activation calls to Billmate

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#34]
There should be a setting if you want to enable/disable (ActivatePayment,CancelPayment,CreditPayment) call to be sent to Billmate when a order is changed in WooCommerce. Many customers do not want a sync beetween WooCommerce and Billmate when order status is changed in WooCommerce.

![image](https://user-images.githubusercontent.com/13320183/90124349-89664000-dd60-11ea-9cbe-557372f1790c.png)

**Comment by NiklasHogefjord** [comment]
@stefanliden Do you mean that customers only might want to use the _activate_ feature but not the _cancel_ feature?

Currently we have it as one single setting but that can be changed if you want.

![image](https://user-images.githubusercontent.com/985946/90221358-5a0c0d80-de0a-11ea-8c07-4d729f3ccd18.png)

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord What @stefanliden means is that the Customers may want to have the option to toggle the single operations off and on.

**Comment by NiklasHogefjord** [comment]
I have a fix for this now in this branch: https://github.com/Billmate/billmate-order-mangement-for-woocommerce/tree/issue-%2334-bco

The settings for it look like this:
![image](https://user-images.githubusercontent.com/985946/92449668-aacd1700-f1ba-11ea-93ad-17126213ff87.png)

Would that be an ok setup for this feature @MattiasNilsson & @stefanliden ?

**Comment by OskarOstlund** [comment]
This at least works from a technical viewpoint, when you turn off the update feature are you not able to update an order in BO from the store and the same is true for the other automatic options. Still waiting response if the setup is acceptable.
