### ISSUE TITLE
Missed Billmate Checkout payment information

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#36]
Thanks page, WooCommerce order, Order confirmation email are not showing Billmate Checkout + payment method.

Example

Billmate Checkout invoice,
Billmate Checkout ParyPayment + Months
Billmate Checkout Swish,
Billmate Checkout DirectPayment / Trustly

![image](https://user-images.githubusercontent.com/13320183/90125765-d8ad7000-dd62-11ea-9020-458e45d64698.png)
![image](https://user-images.githubusercontent.com/13320183/90126028-478ac900-dd63-11ea-8027-76285baff615.png)

**Comment by NiklasHogefjord** [comment]
@stefanliden So it should be named:

[Title set in plugin settings] [ Payment method selected in BCO]

Correct?

As for the last image (on the order page) I don't think that is possible to filter/change, but I will look into it.

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord This is correct.
