### ISSUE TITLE
Duplicate code fragment in assets/js/bco-checkout.js

### ISSUE THREAD

**Issue by MattiasNilsson** [Billmate/billmate-checkout-for-woocommerce#4]
On rows 72 https://github.com/Billmate/billmate-checkout-for-woocommerce/blob/master/assets/js/bco-checkout.js#L72 and 88 https://github.com/Billmate/billmate-checkout-for-woocommerce/blob/master/assets/js/bco-checkout.js#L88 there are duplicate code fragments. 

This needs to be either added as a function or streamline into a single way of handling.

**Comment by Kristian-Andersson** [comment]
Fix: https://github.com/Billmate/billmate-checkout-for-woocommerce/commit/34d4dad0739c5af3a61cfdb66209d6b8aeb6d2cc
