### ISSUE TITLE
cancelPayment API calls still lacks version and client. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#44]
Related to [# 20](https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/20)

As can be seen in this API call 
 

apiLogsid | 38516368
-- | --
Billmate ID (id) | 17882
Funktion | cancelPayment
params | { 	"number": "549120" }
hash | be77828985965cacea106d0bd08fd142a0ace6729313a97a76aaf8b182857f60246e9040773d2b960ac4a72c792fc4d133a6db68155f3518aa548a532bffd5f9
Respons | { 	
        "credentials": { 
              "hash": "48088cadfd1175abedcc223d081c56a27699c1f3bd4c9592b531b43646a6951d758267ff5e19bb7f95721aaefac42e6a54f60cff31cab762ec146088d25398d0", 
              "logid": 38516368 
       }, 	
       "data": { 
              "number": "549120",
              "orderid": "253", 
              "status": "Cancelled",
              "url": "https:\/\/api.billmate.se\/invoice\/17882\/20200820048fe1b6212f5349b45ac37bb24b8307" 	
       }
}
Datum tid | 2020-08-20 10:30:02
test | True
Requesttid klient | 0.00000
Svarstid server | 0.99999
Ursprungliga parametrar | Hämta JSON

is there neither a version nor client attached to the log as was fixed in issue 20 for the other API calls listed in that ticket.

**Comment by NiklasHogefjord** [comment]
@OskarOstlund You need to use the current version of this plugin to check this: https://github.com/Billmate/billmate-order-mangement-for-woocommerce. Can you test again?

**Comment by OskarOstlund** [comment]
Having pulled the latest version of the master branch both in order management and checkout do I not even get any "Billmate reservation was successfully cancelled is created." notification nor is the order cancelled in BO. This is despite me first setting the order as Processing/Behandlas, then setting the status as cancelled/avbruten. 

Or do you have it committed to another branch?

**Comment by NiklasHogefjord** [comment]
@OskarOstlund You should not need to set the order status to "Processing" first. Can you see that the order is successfully placed initially, before you try to cancel it from WooCommerce?

The order notes should look something like this if everything is ok:

![image](https://user-images.githubusercontent.com/985946/91698068-6a461b80-eb72-11ea-8aeb-c5f446f5cfac.png)

**Comment by OskarOstlund** [comment]
![image](https://user-images.githubusercontent.com/58035708/91700126-aaf36400-eb75-11ea-86ea-d6eb08e7bb32.png)
Even a successful order that is made as "Processing" without my help is not given the correct return nor do I see any changes on BO. 

And if it does not need to be "processing" before we update it maybe we should change the order management introduction page that claims that an order needs to be processing.

**Comment by NiklasHogefjord** [comment]
I tested now. Here is the data we send and receive in the cancel request:

```
09 - 03 - 2020 @ 16: 43: 23 - {
	"id": "217327",
	"type": "POST",
	"title": "BOM cancel payment",
	"request": {
		"headers": {
			"Content-Type": "application\/json"
		},
		"method": "POST",
		"body": {
			"credentials": {
				"id": "17882",
				"hash": "d661a04e386c9fe2a8a07710f17ebc15196eba0fd9f4901213195c5e6de4a1a078145bebca22aa371b586a7c24b880ef7034a9f4d42bd385c679853f3b712bbc",
				"test": "true",
				"version": "WordPress: 5.5.1. WooCommerce: 4.4.1. BOM:1.0.0. PHP Version: 7.3.16. Krokedil",
				"client": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/85.0.4183.83 Safari\/537.36"
			},
			"data": {
				"number": "217327"
			},
			"function": "cancelPayment"
		},
		"timeout": 10
	},
	"response": {
		"body": {
			"credentials": {
				"hash": "f362f8428bd97c53743c8fdb363f7322cef623bb0d3096a8be23246bac94fcb4887e893e46df20040c06be3d5d227663486ddbb585972583029e1910cd2d6c73",
				"logid": 39078581
			},
			"data": {
				"number": "217327",
				"orderid": "936537",
				"status": "Cancelled",
				"url": "https:\/\/api.billmate.se\/invoice\/17882\/202009033f2b21f68451acedff6dab91797dfd5e"
			}
		},
		"code": 200
	},
	"timestamp": "2020-09-03 14:43:23",
	"plugin_version": "1.0.0"
}
```
The order notes for the order looks like this:

![image](https://user-images.githubusercontent.com/985946/92130413-fec7ac80-ee04-11ea-944f-65d206536b13.png)

I have updated the Order Management plugin so no cancel request is sent to Billmate if the order hasn't been payed for.

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord This one is now approved according to me!

**Comment by NiklasHogefjord** [comment]
Thanks!
