### ISSUE TITLE
custom payment method does not empty the cart.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#49]
A customer can in BO have their own custompayment method in the checkout that is not sent to BO. This could for instance be an alternative to place the order online and pay in a physical store when you pick up your order. As this does not concern billmate is no information sent to BO but an order is created in the store as it should.
 
![image](https://user-images.githubusercontent.com/58035708/91127961-94e23100-e6a7-11ea-8d46-4e7b19e75329.png)
However one issue arises when the order is placed, namely that the cart is not emptied. This can be seen in the image above where on the left can we see the cart with the articles still present despite as can be seen on the right that the order is placed in the store.  While the order itself is completed and you cannot place it again unless you add or remove an article to the order could there still be confusion for the customers. It could also result in a customer returning and placing a new order and getting the first order included in the new one. 

You can also go back to the page and then pay with another method which will result in the order showing up in BO however no new order is placed in the store.

**Comment by NiklasHogefjord** [comment]
@OskarOstlund I'm not sure I understand. What other payment method did you use to create this order displayed in the image?

**Comment by OskarOstlund** [comment]
You could either use custompayment method, or you could use a card payment and with the Swedbank test card
Card number: 5226612199533406
Expiry: 09/28
CVC: 602
and select a payment that fails, any method that begins a purchase but does not complete it that I have tried yields this result.

**Comment by NiklasHogefjord** [comment]
After discussion with @MattiasNilsson we decided to close this ticket without solving it at the moment.
