### ISSUE TITLE
Wrong indentation for method load_scripts() in Billmate_Checkout_For_WooCommerce 

### ISSUE THREAD

**Issue by MattiasNilsson** [Billmate/billmate-checkout-for-woocommerce#5]
Row 237 to 274 are having one indentation too much https://github.com/Billmate/billmate-checkout-for-woocommerce/blob/master/billmate-checkout-for-woocommerce.php#L238

This needs to follow the rest of the class and PHP files.

**Comment by Kristian-Andersson** [comment]
Fix: https://github.com/Billmate/billmate-checkout-for-woocommerce/commit/417979d6b36bf8f4f027a0dbcc06c1e3f2b0f727
