### ISSUE TITLE
It is currently possible to leave a completed order before success URL, this does not update the order number.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#50]
![image](https://user-images.githubusercontent.com/58035708/91267497-cc1e1400-e773-11ea-98c7-3c6de08c6487.png)
As can be seen in the results above is it currently possible to create an order, and press the place order button in the checkout but leave before you are redirected to the success URL. This results in no update order being sent to BO not updating the order number.  You cannot even attempt to update the order from the store however no feedback is given and the list to the right reports that the order has either been canceled, completed, or whatever successfully. 

![image](https://user-images.githubusercontent.com/58035708/91269371-4d2ada80-e777-11ea-8b2a-6975487c8577.png)
You can add more items to the cart however would you then go back to the checkout will you then be redirected to a successURL, This will update the order in BO and give it the correct ordernumber as can be seen in the picture above. 

![image](https://user-images.githubusercontent.com/58035708/91270285-b3fcc380-e778-11ea-90fb-7c1da1e5ab08.png)
Would you however place another order in between adding the order to BO and the store and going back to the checkout will no update payment API call be sent. Resulting in BO having a different ordernumber than the store. This is easiest achieved by adding the order and then going to another page before you are redirected to the success URL and then completing a second order in an incognito mode tab.

**Comment by NiklasHogefjord** [comment]
This should be fixed now in d08c00560bfb91d4d0a436e03b542ed220ef05a5

**Comment by OskarOstlund** [comment]
This at least works for invoices and part payments, I assume it would also work for bankpayments and cardpayments when they have been fixed too but that would need to be tested then.

**Comment by NiklasHogefjord** [comment]
I have updated the flow now @OskarOstlund and merge the changes into master branch. This was the PR for the change: https://github.com/Billmate/billmate-checkout-for-woocommerce/pull/64
