### ISSUE TITLE
Order Management doesn't work. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#52]
The order management plugin has stopped working. Currently would you try to cancel, activate, or credit an invoice will no information be sent to BO nor will the store get a callback answer causing differences between the invoices in BO and the store. 
![image](https://user-images.githubusercontent.com/58035708/92074556-a2d63700-edb6-11ea-9997-99f42419cd1b.png)
This can be seen in the image above where an order was successfully cancelled while in the "Behandlas" status, however despite that did it not display any of the messages from billmate one would expect. This has been tested and is the same for all three forms of management tasks.

**Comment by NiklasHogefjord** [comment]
Hi @OskarOstlund, I just tested and it works for me. I guess this is related to your setup. Did you double check to the that the Order Management plugin is activated and enabled in the plugin settings?

**Comment by OskarOstlund** [comment]
Yes, this was my bad it was on my side as suggested and was easily fixed.
