### ISSUE TITLE
Cardpayments no longer work

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#53]
Would you currently attempt to make a cardpayment will you be met with the following message: 
![image](https://user-images.githubusercontent.com/58035708/92076757-580aee00-edbb-11ea-8309-d8d7cd650a86.png)

**Comment by NiklasHogefjord** [comment]
Closing this since it seems to be a temporary Billmate issue. Not related to the plugin.
