### ISSUE TITLE
Paying for the same order twice results in two orders being placed in BO.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#56]
Would you attempt to make a purchase with the payment module and begin to make a payment but not finishing the order and then opening the checkout in another window before finishing both orders will no longer an error message show up, instead is only one order placed in the store as is correct, however two orders are created in BO.

**Comment by NiklasHogefjord** [comment]
That is correct @OskarOstlund. I don't see how we could limit/prevent this from happening in some other way. Do you have a suggestion on what would happen in this scenario?

**Comment by MattiasNilsson** [comment]
I agree with @NiklasHogefjord it is very hard to circumvent, therefore let´s close this one.
