### ISSUE TITLE
You cannot update person being invoiced.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#61]
When you attempt to update an order in Woocommerce, if you tried to update the customer's name or address, either due to a mistake being made or due to a move will this not be included in an update. This should preferably be made so one could update this independently of the items that are purchased. For an example would one only need to change the address should one be able to do so without needing to press the "räkna om" button like how one would normally update an order with items to avoid confusion for the user.

**Comment by NiklasHogefjord** [comment]
@OskarOstlund Does Billmate support changing of customer address if the selected payment method is Invoice or part payment?

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord Yes that is possible today through the API.

**Comment by NiklasHogefjord** [comment]
This should have been fixed in 93eec7461a4c436ce33370f4965973e31c3f0d4d.

**Comment by OskarOstlund** [comment]
Tested and approved-
