### ISSUE TITLE
Changing decimal rounding in woocommerce returns rounding error. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#62]
![image](https://user-images.githubusercontent.com/58035708/92691063-4b017800-f342-11ea-8249-948302ba32f7.png)
Would you change your settings to include only one decimal in the price in woocommerce will you be met with the error message above. This ought to be fixed.

**Comment by NiklasHogefjord** [comment]
I suggest that we don't allow 0 decimals when using BCO. We can even disable the plugin if the settings is set to 0 decimals.

We will most likely end up in endless of different support tickets if we try to solve some kind of 0 decimal compatibility. This setting in WooCommerce isn't just a cosmetic change in the webstore, it is rounding of net price and tax amount to the nearest even integer.

**Comment by OskarOstlund** [comment]
can we force wooCommerce to only accept 2 decimals then? If that is possible would that be the simplest alternative I would think.

**Comment by NiklasHogefjord** [comment]
Let me look into that.

**Comment by OskarOstlund** [comment]
because the issue also appear if one uses 1 decimal as well.

**Comment by NiklasHogefjord** [comment]
I have looked into this a bit closer @OskarOstlund. Prices are supposed to be sent _without tax_ and the actual _tax rate_.

When using 0 (or 1) decimals in WooCommerce the _price without tax_ and the _tax amount_ is being rounded. To send a rounded number (price without tax) together with the tax rate to Billmate will end up in different prices (including tax) in the two systems.

Should we just mention that 2 decimals is required in the plugin documentation or should we not enable the plugin at all if less than two decimals is set in WooCommerce @OskarOstlund ?

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord I think we should go with the option 2 decimals is required in the plugin documentation.

**Comment by NiklasHogefjord** [comment]
I agree @MattiasNilsson. Thanks!

I'll close this ticket after I've added it to the docs.

**Comment by NiklasHogefjord** [comment]
I realize that this was already added as a required setting in the docs here: https://docs.krokedil.com/article/361-billmate-checkout-introduction. I Will update it in the repository documentation as well when [that issue](https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/6) is closed.
