### ISSUE TITLE
Orders that are set to pending in BO are given the wrong status.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#63]
Would you make an order that are set to pending by the system would it get the status "Paused", however as this is incorrect and technically allows the merchant to edit the order while we are making a credit check. Instead should the order be given the status "Inväntar betalning".

**Comment by NiklasHogefjord** [comment]
"Inväntar betalning" is not a good status to set for this use case. Some stores might have the "Hold stock" setting activated in the store. This means that orders with the status "Inväntar betalning" automatically changes to "Avbruten" after xx amount of minutes.

We don't want stock to accidentally be released for the order. We also need a way to see the difference between an order where the customer has finished the checkout process and one where the customer not yet have finalized the checkout process. 

Personally I think "Pausad" is a good order status for this. This is how we do it in several other payment solutions.

**Comment by OskarOstlund** [comment]
If this is acceptable to @MattiasNilsson am I happy with the current design.

**Comment by MattiasNilsson** [comment]
@NiklasHogefjord @OskarOstlund I agree that this solution is good!

**Comment by NiklasHogefjord** [comment]
Thanks. Closing this.
