### ISSUE TITLE
Checkout update unselects any chosen payment method. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#68]
If I am quick enough, I can select a payment method before the checkout is updated. This does however have the downside that the payment method gets unselected again, and I have to once more select it. This is rather annoying for the customer and if it is possible would it be better if the chosen payment method was selected again or even remained selected automatically.

**Comment by MattiasNilsson** [comment]
When testing through master branch the orderid never gets updated from the temporary orderid.

When testing using an older branch: 0b3a5be70d16ba5c367b55ba7856a56513511bdd as long as you wait for the checkout to load completely before continuing, it works fine, orderid gets updated.
However on this older branch, if you do not wait a little until checkout has loaded completely, we get the same issue that orderid does not get updated.

**Comment by NiklasHogefjord** [comment]
Thanks, I will look into this.

**Comment by NiklasHogefjord** [comment]
I have compared the two versions now. The backend requests are identical so something is probably different in front-end. I will continue troubleshoot this.

**Comment by NiklasHogefjord** [comment]
This should be solved now after updates in Billmate's system (improvements to the validation callback event). I'm closing this issue.
