### ISSUE TITLE
Attempting to press recount causes 500 error. 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#72]
![image](https://user-images.githubusercontent.com/58035708/98940453-4d6f8200-24eb-11eb-94f1-650555b721bb.png)
As can be seen in the image above, would one need to update an order will this now cause a 500 error and no update API call to be sent to BO. Instead is the webstore displaying that the order is being updated and a loading icon that is stuck.

**Comment by NiklasHogefjord** [comment]
Can you send me the log for this request via Slack @OskarOstlund ?
