### ISSUE TITLE
Attempting to refund an order returns a 500 error 

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#73]
Similar to [issues 72](https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/72) has an error shown up where if one attempts to ask for a refund through billmate checkout will the page start to load but no change will be made. Looking into the console list will show that a resource has failed to load and you have gotten a 500 error.

**Comment by NiklasHogefjord** [comment]
Can you send me the log for this refund via Slack @OskarOstlund?
