### ISSUE TITLE
No activatepayment call should be made for the direct payment methods.

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#78]
When a customer pays via directpayment (Swish/Trustly) to Billmate, the money is withdrawn immediately and no activatePayment call needs to be made to Billmate. It seems that the extension today makes an activatePayment call for a directpayment  if you change the status from processed to complete and have enable autocapture = true. 

This is unnecessary and confuses customers  beacuse of the error message in the order quotations (see picture) 

![image](https://user-images.githubusercontent.com/13320183/102363305-95d00300-3fb5-11eb-91b9-776ad2a1b59e.png)

**Comment by MattiasNilsson** [comment]
Solved with: https://github.com/Billmate/billmate-order-mangement-for-woocommerce/releases/tag/0.2.1
