### ISSUE TITLE
Webpage download Href broken.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#8]
https://docs.krokedil.com/article/361-billmate-checkout-introduction
In the webpage above is there a link that is supposed to download the module. However currently is the link broken and only direct you to #.

**Comment by MichaelBengtsson** [comment]
We will make sure that this is working when the plugin is released for people to start using it. At the moment i believe we are only doing internal testing?

**Comment by MattiasNilsson** [comment]
@MichaelBengtsson That is correct.

**Comment by andyjohansson** [comment]
Closing this issue since we are moving documentation to the official documentation page from Billmates domain.
