### ISSUE TITLE
Verify that "partially pay from XXX SEK" works on product page

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/billmate-checkout-for-woocommerce#83]
**Requirements**
* Should use data from getPaymentplans API function.
* Should not be shown if getPaymentplans API function returns no available payment plans. For example if amount of product is too low.
* Should update the amount if the product page includes a variable product that affects the price of the product. For example maybe a red variant of a pair of paints costs + 100 SEK.
* Should only be shown if currency used is SEK since that is the only available currency for part payment.

**Comment by MattiasNilsson** [comment]
This have been tested and the leftovers are added to a separate ticket: https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/86
