### ISSUE TITLE
Verify that the used payment option is displayed on the order

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/billmate-checkout-for-woocommerce#85]
Why?
Fot he shop owner to more easily get statistics from WooCommerce. Just "Billmate Checkout" is not that informative.

**Comment by DanielMarklund** [comment]
Some more why's: The payment method information is currently being used in Nemo (ERP) in the previous Billmate Checkout plugin to identify the payment method. For customer support, it really helps to see exactly which method has been used both on the _order view_ and _orders list view_.

**Comment by andyjohansson** [comment]
Is this implemented @NiklasHogefjord?

**Comment by NiklasHogefjord** [comment]
Yes @andyjohansson, it seems to have been a duplicate of issues. Fixed and closed here: https://github.com/Billmate/billmate-checkout-for-woocommerce/issues/93

**Comment by andyjohansson** [comment]
Ok, closing!
