### ISSUE TITLE
Partial payment function pay from xxx logo is missing on the product page.

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#86]
We do not have a function to display the partial payment logo "pay from xxx" on a product page.

We should have a setting to enable this function so a customer can see what they can pay from in month for the product.
The product price should only appear if it matches the merchans paymentplans and always show the minimum price to pay in month. It should also be a setting to set where the partial payment logo should be displayed on the page.

To know which price matches your partial payment plan, you can make a call to getpayment plan.
https://developer.billmate.se/api-integration/getpaymentplans/

An important note is that it should also work to show the partial payment logo if you are a logged in the shop and that it is update the price of a product if the product has different prices depending on attributes.

If you want to read how it works in our old extension and how it works, you can read more here in section 3.9 https://support.billmate.se/hc/sv/articles/360007661437-3-Billmate-Checkout-WooCommerce

Example on a merchants store
![image006](https://user-images.githubusercontent.com/13320183/102984204-88fb6400-450d-11eb-8652-c4e181aa7d29.jpg)

Logo 

![bm_delbetalning_l (2)](https://user-images.githubusercontent.com/13320183/102984211-8a2c9100-450d-11eb-8357-cc743be76585.png)

**Comment by NiklasHogefjord** [comment]
PR for this feature is now available here - https://github.com/Billmate/billmate-checkout-for-woocommerce/pull/88
