### ISSUE TITLE
Pop module "Do you really want to leave the page" when making payment?

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#87]
Nvmaskin.se has had the following problems. When you make a payment, a text box appears that says if you really want to leave the page. If you then click yes, you will be directed to the thank you page. What creates problems is that the bankID singing does not come up and the same happens when you have to pay with Swish. If you instead choose not to leave the page, for example, bankID/Swich signing will appear and you can complete the purchase normally.

Nvmaskin.se developer wrote following to our support. 

Hej,
Jag har testat att både tömma cache och inaktivera cache-tilläggen helt men det verkar inte fungera ändå.
Det jag kan se är att det blir ett js-fel i consolen när man fyller i telefonnumret:
Uncaught TypeError: Cannot read property 'zip' of undefined at handleEvent (bco-checkout.js:92)​
Betalmodulen laddar alltid om (tror jag) och man måste ange telefonnumret en andra gång.
När man försöker slutföra köpet så får man upp en dialogruta som frågar om det är okej att dirigera om till en annan sida för kortuppgifter. Men det händer aldrig utan kassasidan laddar bara om. Det finns inga custom omdirigeringar i koden som vi har gjort.

Det går att genomföra själva Swish-betalning men som kund får man ingen bekräftelse.

Skickar med en debug-log. (Kan själv inte utläsa något fel).

[Billmate_Checkout-2020-12-28-c09962ab5bcbc6a2cf3079812fe0bb23.log](https://github.com/Billmate/billmate-checkout-for-woocommerce/files/5750128/Billmate_Checkout-2020-12-28-c09962ab5bcbc6a2cf3079812fe0bb23.log)

**Comment by NiklasHogefjord** [comment]
@stefanliden & @MattiasNilsson when I test I don't get redirected to thank you page. If I click "Yes" I will see the checkout page again. If I click "No" the checkout process will proceed and I can sign with Bank ID.

I think this is an isolated issue on the merchant site. Me and Mattias are communicating over Slack to try to solve it.

**Comment by NiklasHogefjord** [comment]
Just adding how the alert box looks like:
![image](https://user-images.githubusercontent.com/985946/103872743-18d50c80-50cf-11eb-9d63-1ba106b19026.png)

**Comment by andyjohansson** [comment]
Please follow up this as soon as you are back next week @stefanliden.

**Comment by stefanliden** [comment]
I have asked the customer if ftp access is waiting for feedback 👍

**Comment by NiklasHogefjord** [comment]
We got login to the staging site. The can not be recreated there.

We had a similar issue with another iframe based checkout (with the same checkout flow) and there it seems as the Google Tag Manager plugin was causing a reload of the page in this sequence (that was causing this error).

**Comment by andyjohansson** [comment]
Ok, so there are no known workarounds? Can @stefanliden talk to the customer and see if we can verify that it is Google Tag Manager? 

Are there any ways to work around this @NiklasHogefjord?

**Comment by NiklasHogefjord** [comment]
We have an idea on how to solve this. We implemented a slight change in how we submit the WooCommerce checkout form in the other plugin that seems to have solved the problem. I can have a look at this in a couple of days.

**Comment by andyjohansson** [comment]
Ah great. Let's plan this then for the 1.0.1 release if no other urgent things come in between.

**Comment by stefanliden** [comment]
Tested and this works well :)
