### ISSUE TITLE
Billmate Checkut Settings cant be translated

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#89]
These texts below cannot be translated via Loco Translate

![image](https://user-images.githubusercontent.com/13320183/105024307-3b124700-5a4c-11eb-8215-85714c8210cf.png)
![image](https://user-images.githubusercontent.com/13320183/105024339-45ccdc00-5a4c-11eb-8fb2-fb0c70dc108c.png)

**Comment by andyjohansson** [comment]
What's the status here @NiklasHogefjord?

**Comment by NiklasHogefjord** [comment]
POT file updated now @andyjohansson. I have pushed it to Master branch.

**Comment by andyjohansson** [comment]
Can you verify @stefanliden?

**Comment by andyjohansson** [comment]
@MattiasNilsson will add .mo file and submit a pull request so @NiklasHogefjord can verify.

**Comment by MattiasNilsson** [comment]
Added a PR to fix this: https://github.com/Billmate/billmate-checkout-for-woocommerce/pull/107
