### ISSUE TITLE
Bank and Cardpayment gives error message gets the checkout stuck in success URL.

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#9]
![image](https://user-images.githubusercontent.com/58035708/87506159-ecce5680-c66a-11ea-873a-378c6b318813.png)

Would an user make either a bank or a cardpayment in the checkout will an error message appear as can be seen above. However despite the error message will an order be placed both on BO and in the store.

![image](https://user-images.githubusercontent.com/58035708/87506458-9f061e00-c66b-11ea-9043-0919cda6db50.png)
As can be seen above are there discrepancies in the orders as well, in the top row taken from the store does the order have the order number 12 while it is registered as 0 in BO. Would you do this and then return to the checkout will you be met with a success screen, effectively locking you out of further purchases.

**Comment by NiklasHogefjord** [comment]
Wrong hook was used to redirect customer to thank you page. This should be fixed now.

**Comment by NiklasHogefjord** [comment]
The rewrite in the plugin plus a change in how an updated order ID is handled in Billmates system should have solved this issue.

**Comment by NiklasHogefjord** [comment]
I think we can close it. Do you agree @OskarOstlund?

**Comment by MattiasNilsson** [comment]
This is now done.
