### ISSUE TITLE
Checkout does not work with WooCommerce Smart Coupons

### ISSUE THREAD

**Issue by OskarOstlund** [Billmate/billmate-checkout-for-woocommerce#90]
Would you use the plugin "Woocommerce Smart Coupons" as one of our biggest customer does, does this plugin not work with our checkout currently. Would you apply the coupon before going to the checkout in the cart will you be met with the following view when entering the checkout:
![image](https://user-images.githubusercontent.com/58035708/105188454-37f28600-5b34-11eb-82f0-9528553f50bc.png)

Similarly would you attempt to apply it in the checkout will the calculation of the new price simply lock in an endless loop and the following error message be recorded in the console log:
![image](https://user-images.githubusercontent.com/58035708/105188803-915ab500-5b34-11eb-920b-7562ac5971b4.png)

**Comment by stefanliden** [comment]
This is still a problem. As I see it, there are three different types of problems that can occur when entering the discount code.

The first problem (image error1) is that you are in the shopping cart page and enter the discount code and then go to the Billmate Checkout page. Then there will be an error message that Total Sum with Tax is not equal to Total Sum Excluding VAT,

I think this error has to do with us not doing the right calculation with the rebate code extension in the initCheckout / UpdateCheckout call.

// See attached InitCheckout / updateCheckout call

The second problem (image error 2) is if you go directly to Billmate Checkout and then fill in the rebate code. Then the order summary will just spin in an eternal loop. To break the loop, you need to fill in your information in Billmate Checkout.


If this cannot be solved in a good way, it might have been good with a notice that you have to fill in your information in Billmate Checkout for the "loop" to disappear.

The third problem (image error 2) that is related to the steps you do problem 2. When you get to Billmate Checkout Step 2 where you choose the payment method, Billmate Checkout has not included the discount code in the total amount.

I also think this error has to do with us not doing the right calculation with the rebate code extension in the initCheckout / UpdateCheckout call.

// See attached InitCheckout / updateCheckout call



![erro2](https://user-images.githubusercontent.com/13320183/105826667-47088680-5fc1-11eb-9f30-32d19f3dcf20.png)
![error1](https://user-images.githubusercontent.com/13320183/105826669-47a11d00-5fc1-11eb-8417-66819894b416.png)

**Comment by NiklasHogefjord** [comment]
There is no standard way to handle gift cards in WooCommerce. Each Gift card plugin has its own way of implementing usage of gift cards. When the payment processor requires all order lines to be sent this will cause issues.

Basically this means that we need to implement support for gift cards on a per plugin basis. I will look into support for Smart coupons to start with.

**Comment by NiklasHogefjord** [comment]
@stefanliden PR added now that will solve this https://github.com/Billmate/billmate-checkout-for-woocommerce/pull/102

**Comment by andyjohansson** [comment]
Like! Please verify this @stefanliden 👍

**Comment by OskarOstlund** [comment]
This is verified and works.
