### ISSUE TITLE
Being able to checkout free orders

### ISSUE THREAD

**Issue by DanielMarklund** [Billmate/billmate-checkout-for-woocommerce#92]
In the previous Billmate Checkout plugin, it's not possible to checkout if the order is free of charge (afaik). Due to that, gift card plugins and the standard WooCommerce coupons don't work if the order cost goes down to 0 kr. Is it possible to checkout free orders in this plugin? If no, then that's a feature request from us.

**Comment by NiklasHogefjord** [comment]
Hi Daniel, I have created a Pull Request that will solve the 0 kr issue: https://github.com/Billmate/billmate-checkout-for-woocommerce/pull/94.

@MattiasNilsson does it look ok?

**Comment by andyjohansson** [comment]
This is now merged into the master branch. Could you please verify the functionality @DanielMarklund?

**Comment by MattiasNilsson** [comment]
This is now solved with the Pul Request https://github.com/Billmate/billmate-checkout-for-woocommerce/pull/94
