### ISSUE TITLE
Hide delivery address setting in Billmate Checkout settings

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#95]
One of our customers who sells digital products has a wish that you should be able to turn off the delivery address field from the Billmate Checkout settings. We have a function in the initch checkout called hideShippingAddress = true / false. This makes the delivery address field visible or not at checkout. It would have been good if we could add a text box in the settings where you can choose whether this should be visible or not.

     "data": {
         "CheckoutData": {
             "terms": "https://yourclient.com/terms",
             "privacyPolicy": "https://yourclient.com/privacepolicy",
             "redirectOnSuccess": "true",
             "hideShippingAddress": "true"
         },

This should be the result when hideShippingAddress = true
![image](https://user-images.githubusercontent.com/13320183/105361353-e6acca00-5bf9-11eb-8260-8fc18e64bfcb.png)

**Comment by NiklasHogefjord** [comment]
I've tested this but even though I send in the following (in _init_ request):

`"CheckoutData": {
					"terms": "https:\/\/krokedilserver1.se\/",
					"companyView": "false",
					"hideShippingAddress": "true",
					"privacyPolicy": "https:\/\/krokedilserver1.se\/"
				},
`
I still se this checkout:

![image](https://user-images.githubusercontent.com/985946/109480076-60e33080-7a7b-11eb-9d52-6285a2bb3d6f.png)
