### ISSUE TITLE
Turn off Billmate updating customer data in Woocommerce after making a order

### ISSUE THREAD

**Issue by stefanliden** [Billmate/billmate-checkout-for-woocommerce#96]
A customer has a wish that they can turn off Billmate updating customer data in Woocommerce after completing a payment / order.

This is desirable because their customers are logged in when they make a purchase, it is a requirement to even be able to complete the purchase. Say that stefan with social security number 8711111-1111 is logged in and makes a purchase, but in the Billmate checkout, a family member Ali pays 90-111111-1111. Then Billmate will change the name, address and phone number used on WordPress

**Comment by NiklasHogefjord** [comment]
Thanks for the suggestion @stefanliden. I think we need to discuss this a bit closer before we start the development for this. So I get a grip of the feature in detail :).

**Comment by andyjohansson** [comment]
We need more input here from the customer @stefanliden. Are the users logged in? Are they using some kind of quote functionallity? Please setup a discovery call with the client and @NiklasHogefjord so we can get the full picture.

**Comment by andyjohansson** [comment]
Any updates here @stefanliden? How did the meeting with the customer go? Any new insights?

**Comment by NiklasHogefjord** [comment]
@stefanliden You can test this feature by using this branch: https://github.com/Billmate/billmate-checkout-for-woocommerce/tree/issue-96.

You also need to add this code snippet to your WordPress website to test the feature: 

```
add_filter('bco_populate_address_fields', 'custom_bco_populate_address_fields');
function custom_bco_populate_address_fields() {
  return 'no';
}
```

You can do this via custom code or via the plugin [Code Snippets](https://sv.wordpress.org/plugins/code-snippets/).

**Comment by andyjohansson** [comment]
Customer will test tomorrow according to @stefanliden ✌️

**Comment by andyjohansson** [comment]
Customer have approved and we should be able to ship this.

**Comment by andyjohansson** [comment]
@stefanliden will check with merchant for release.

**Comment by andyjohansson** [comment]
Documentation here in Swedish: https://support.billmate.se/hc/sv/articles/360018444977-St%C3%A4ng-av-att-Billmate-uppdaterar-kunddatan
