### ISSUE TITLE
Add verified compatible plugins to readme.md for WordPress Repo

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/billmate-checkout-for-woocommerce#99]

**Comment by andyjohansson** [comment]
Do you have any input here @NiklasHogefjord?

**Comment by NiklasHogefjord** [comment]
I'll take a look @andyjohansson

**Comment by NiklasHogefjord** [comment]
Support for the following plugins at the moment:
* WooCommerce Sequential Order Numbers - https://wordpress.org/plugins/woocommerce-sequential-order-numbers/
* Sequential Order Numbers Pro - https://woocommerce.com/products/sequential-order-numbers-pro/
* Smart Coupons - https://woocommerce.com/products/smart-coupons/
* WooCommerce EU VAT Number - https://woocommerce.com/products/eu-vat-number/

**Comment by andyjohansson** [comment]
Thanks, I have now added this to the documentation.
